name: dotnet build

env:
  SOLUTION_PATH: './src/BlazingPizza.sln'
  DOTNET_VERSION: '7.x'
  APP_NAME: 'devint-blazor-workshop'

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
           fetch-depth: '1'

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '${{ env.DOTNET_VERSION }}'
          include-prerelease: true

      - name: Install dependencies
        run: dotnet restore '${{ env.SOLUTION_PATH }}'

      - name: Build with dotnet
        run: dotnet build '${{env.SOLUTION_PATH}}' --configuration Release

      - name: dotnet publish
        run: dotnet publish '${{env.SOLUTION_PATH}}' --no-build -c Release -o ${{env.DOTNET_ROOT}}/myapp /p:DebugType=None /p:DebugSymbols=false

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-app
          path: |
            ${{env.DOTNET_ROOT}}/myapp            
            !${{env.DOTNET_ROOT}}/myapp/**/*LICENSE*

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: dotnet-app
          path: download/dotnet-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.APP_NAME}}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9FEDFBECDB154C0E80572E6E89091151 }}
          package: download/dotnet-app